### ISSUE TITLE
Error on noisy signal with silence_removal

### ISSUE THREAD

**Issue by bagustris** [MaxStrange/AudioSegment#11]
First, thanks to your great works making pydub easy to use.

For noisy signal (wav file contains more noise than voice), the audiosegment `filter_silence` gives an error. Yes, it is make a sense. But, it will be better to give warning and return the originial signal. The needed step is to check whether there is silence below threshold or not, if not, return the original signal.

The error message is, 
`CouldntDecodeError: Couldn't find data header in wav data`

This error message is gone when I make the threshold smaller (e.g. 0.1) for noise-corrupted speech, but for noisy signal it will gives error.

**Comment by MaxStrange** [comment]
Done! Should be fixed in version 0.18.0. I think the silence filter is removing too many samples from the WAV file when the threshold is too high. I just issue a warning now like you suggest and return a copy of the original file.

**Comment by bagustris** [comment]
I think this bug appears again in the latest release (`0.22`). Using filter_silence, if there is no amplitude of signal below the percentage (`threshold_percentage`) and minimum duration (`duration_s`), it gives an empty list.
```
>>> seg = audiosegment.from_file(f)
>>> seg_f = seg.filter_silence(duration_s=0.001, threshold_percentage=3)
>>> x = seg_f.to_numpy_array()
>>> x
array([], dtype=int16)

```
Instead of empty list, the previous solution (throw a warning and return original samples) should be better.

**Comment by MaxStrange** [comment]
This is actually not exactly the same bug. That bug remains fixed, as you can see from the reproduction below:

```python
>>> import audiosegment
>>> seg = audiosegment.from_file("furelise.wav")
>>> seg.filter_silence(threshold_percentage=99.9)
<stdin>:1: UserWarning: After silence filtering, the resultant WAV file is corrupted, and so its data cannot be retrieved. Perhaps try a smaller threshold value.
furelise.wav: 1 channels, 16 bit, sampled @ 44.1 kHz, 211.984s long
>>>
```

The result of this code is a warning and the original recording being returned, just like before.

For some reason, we are able to read in your file after filtering the silence via SOX, even though there aren't any samples in it. Hmmm.

Could you perhaps point me to a sound file that I can reproduce this issue on? Perhaps you could share the sound file you are using?

**Comment by bagustris** [comment]
Dear @MaxStrange, thanks for replying. 

I tried on several machines, only one fails with this error. This machine is jetson agx with ARM8 chip. Other x64 machines give the warning. This exactly same as previous. Here is an example using a sound file from [1].

```
In [28]: f = 'Eider_rodriguez.wav'

In [29]: seg = audiosegment.from_file(f)

In [30]: seg_f = seg.filter_silence(duration_s=0.01, threshold_percentage=1)

In [31]: seg_f
Out[31]: Eider_rodriguez.wav: 1 channels, 16 bit, sampled @ 48.0 kHz, 6.102s long

In [32]: seg_f = seg.filter_silence(duration_s=0.01, threshold_percentage=99)

In [33]: seg_f
Out[33]: Eider_rodriguez.wav: 1 channels, 16 bit, sampled @ 48.0 kHz, 0.000s long

```

I tried to uninstall and reinstall audiosegment v0.22 but it gives the same result.
The same result applied when I downgrade to audiosegment v0.18.
Is there any way to debug or find out where is the problem?

[1] https://commons.wikimedia.org/wiki/File:Eider_rodriguez.wav

**Comment by MaxStrange** [comment]
Sorry it's taken me so long to get to this. I've been super busy at work and with the kids.

I can actually reproduce this bug on a fresh install of Raspberry Pi OS on an RPi4 (which, like the Jetson, has an application level ARM chip in it). So it probably means that the ARM build and the x86 build for SOX behaves slightly differently. There's nothing I can do about that, unfortunately.

So I think I'll push out a revision that fixes it by manually checking to see if there are zero samples in the result. That should fix it.

**Comment by MaxStrange** [comment]
Done. Version 0.23.0 should have a fix for you. Let me know if it isn't working or something.
