### ISSUE TITLE
audiosegment.from_file cannot work with readers

### ISSUE THREAD

**Issue by nbraud** [MaxStrange/AudioSegment#9]
I use `argparse.FileType` to properly enforce that file (paths) passed as parameters exist, are readable, ...
As such, I do not have a `Path` object to pass to `from_file`, but an `_io.BufferedReader` or somesuch.

Generally, it would be expected to be able to pass a reader, as we might be working with in-memory data & such.

**Comment by nbraud** [comment]
PS: I ended up being able to solve my problem using only vanilla `pydub`.

**Comment by MaxStrange** [comment]
@nbraud How did you end up solving the problem? It may be helpful for others.
